/**
 * We will use the glider gun with period-60.
 *
 * We could use the period-30 gun
 * but for performance reasons let's use 60.
 * The less a period the fewer gliders are on the screen,
 * hence the fewer cells' positions to recalculate.
 *
 * It will be useful on the big circuits
 * such as half-adder and full-adder.
 */
export const gliderGunP60 = `
............................O..........
............................O.O........
...........OO..................OO......
.........O...O.................OO....OO
...OO...O.....O................OO....OO
...OO..OO.O...O.............O.O........
........O.....O.............O..........
.........O...O.........................
...........OO..........................
.......................................
.......................................
.......................................
.......................................
.......................................
.......................................
.......................................
..........O.O..........................
.........O..O...OO.....................
OO......OO.....OOO.OO..OO..............
OO....OO...O...O...O...O.O.............
........OO.....O.O........O............
.........O..O..OO......O..O............
..........O.O.............O............
.......................O.O.......OO....
.......................OO........O.O...
...................................O...
...................................OO..`;

export const metadata = {
  period: 60,
  sizeX: 39,
  sizeY: 27,

  /**
   * 2 vertical opposed Glider Guns will cancel each other's streams
   * if the left one is 1 cell lower that the right,
   * and the distance between them is (10 * N) + `cancelX`.
   */
  cancelX: 8,
  cancelY: 1,

  /**
   * Since a glider has the period of 4,
   * we can safely move the gun 1 cell diagonally
   * changing the phase by 4 for each moved cell.
   * (Move 1 cell to top-left, increase phase by 1.)
   */
};
